Models/SubTask.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class SubTask {
    [Key]
    public int Id { get; set;}
    [Required]
    [StringLength(100)]
    public string Title { get; set; } = "";
    [Required]
    public string Description { get; set; } = "";
    public DateTime Created_At {get;set;}
    public DateTime Start_Date { get; set;}   
    public DateTime End_Date {get; set;} 
    public DateTime Update_Date {get; set;}
    public string? Status {get;set;}
    
    // Navigation Properties
    public Task? Task { get; set;} 
    public SubTaskWeight? SubTaskWeight {get;set;}
    public List<SubTaskFile>? SubTaskFiles {get; set;}

    // Foreign Keys
    [ForeignKey("Task")]
    public int TaskId {get;set;}
    public string? Created_by {get;set;}


}

Controllers/SubTaskController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

public class SubTaskController : Controller {
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;
    private readonly ApplicationDbContext _dbContext;
    public SubTaskController(
        UserManager<ApplicationUser> _userManager,
        RoleManager<ApplicationRole> _roleManager,
        ApplicationDbContext _dbContext){
            this._userManager = _userManager;
            this._roleManager = _roleManager;
            this._dbContext = _dbContext;
        }
    public IActionResult Create(){
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(SubTaskModel model,int Id,List<IFormFile> subtaskfiles){
        if (ModelState.IsValid){
            SubTask subTask = new SubTask(){
                Title = model.Title,
                Description = model.Description,
                Start_Date = model.Start_Date,
                End_Date = model.End_Date,
                Created_At = DateTime.Now,
                Update_Date = DateTime.Now,
                TaskId = Id,
                Status = "Pending",
            };
            _dbContext.SubTask.Add(subTask);
            _dbContext.SaveChanges();
            SubTaskWeight sb = new SubTaskWeight(){
                SubTaskId = subTask.Id,
                Point = model.Point,
            };
            _dbContext.SubTaskWeight.Add(sb);
            _dbContext.SaveChanges();

            // add the subtaskfiles here
            if(subtaskfiles != null){
                foreach(var stf in subtaskfiles){
                    SubTaskFile subtaskfile = new SubTaskFile(){
                        SubTaskId = subTask.Id,
                        FileName = stf.FileName,
                        ContentType = stf.ContentType,
                    };
                    using(var inputstream = new MemoryStream()){
                        await stf.CopyToAsync(inputstream);
                    subtaskfile.Data = inputstream.ToArray();
                    }
                    _dbContext.SubTaskFile.Add(subtaskfile);
                    _dbContext.SaveChanges();   
                    

                }
            }
            var subtasks = _dbContext.SubTask.Where(sb => sb.TaskId == Id).ToList();
            double totalpoint = 0.0;
            foreach(var st in subtasks){
                var stw = _dbContext.SubTaskWeight.FirstOrDefault(sbw => sbw.SubTaskId == st.Id);
                totalpoint += stw.Point;   
            } 

            foreach(var st in subtasks){
                var stw = _dbContext.SubTaskWeight.FirstOrDefault(sbw => sbw.SubTaskId == st.Id);
                stw.Weight = stw.Point / totalpoint * 100;
                _dbContext.SubTaskWeight.Update(stw);
            }
            _dbContext.SaveChanges();
         
        var task = _dbContext.Task.FirstOrDefault(t => t.Id == Id);

        double totalprogress = 0.0;

        foreach(var st in subtasks){
            var stw = _dbContext.SubTaskWeight.FirstOrDefault(sbw => sbw.SubTaskId == st.Id);
            if(st != null){
                if(st.Status == "Completed"){
                totalprogress += stw.Weight;
            }
            } 
         }
            task.Progress = totalprogress;
            _dbContext.Task.Update(task);
            _dbContext.SaveChanges();

            return RedirectToAction("TaskDetail","Task",new{
                Id = subTask.TaskId,
            });
        }
        return View(model);
    }

    [HttpGet]
    public IActionResult Detail(int Id){
        var subtask = _dbContext.SubTask.FirstOrDefault(s=>s.Id == Id);
        var subtaskweight = _dbContext.SubTaskWeight.FirstOrDefault(stw => stw.SubTaskId == subtask.Id);
        var subtaskfiles = _dbContext.SubTaskFile.Where(tf => tf.SubTaskId == subtask.Id).ToList();
        SubTaskDetail sbd = new SubTaskDetail(){
            SubTask = subtask,
            SubTaskWeight = subtaskweight,  
            SubTaskFiles = subtaskfiles
        };
        return View(sbd);
    }
    public IActionResult StatusUpdate(int Id){
        var subtask = _dbContext.SubTask.FirstOrDefault(s => s.Id == Id);
        var subtaskweight = _dbContext.SubTaskWeight.FirstOrDefault(sw => sw.SubTaskId == subtask.Id);
        subtask.Status = "Completed";
        _dbContext.SubTask.Update(subtask);
        _dbContext.SaveChanges();

        var task = _dbContext.Task.FirstOrDefault(t => t.Id == subtask.TaskId);
        task.Progress += subtaskweight.Weight;
        _dbContext.Task.Update(task);
        _dbContext.SaveChanges();

        return RedirectToAction("TaskDetail","Task",new {
            Id = task.Id
        });
    }

    public async Task<IActionResult> GetSubTaskFile(int id){
         var file = _dbContext.SubTaskFile.FirstOrDefault(tf => tf.Id == id);
         if(file != null){
            return File(file.Data,file.ContentType,file.FileName);
         }
         return NotFound();
     }
  
    
}

Views/SubTask/Create.cshtml
@using ProjectManagementApp.Models
@model SubTaskModel

<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Create Your Sub Task Here</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
</section>

    <section class="content">
      <form asp-controller="SubTask" asp-action = "Create" method="post" enctype="multipart/form-data">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-secondary">

            <div class="card-header">
              <h3 class="card-title">Sub Task Detail</h3>
            </div>

            
            <div class="card-body">

            
              <div class="form-group">
                <label for="inputName">Sub Task Title</label>
                <input asp-for="Title" type="text" id="inputName" class="form-control">
              </div>

              <div class="form-group">
                <label for="inputDescription">Sub Task Description</label>
                <textarea asp-for = "Description" id="inputDescription" class="form-control" rows="4"></textarea>
              </div>

               <div class="form-group">
                  <label>Start Date</label>
                    <div class="input-group date" id="reservationdatetime" data-target-input="nearest">
                        <input asp-for = "Start_Date" type="text" class="form-control datetimepicker-input" data-target="#reservationdatetime"/>
                        <div class="input-group-append" data-target="#reservationdatetime" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>

                  <!-- Date and time -->
                <div class="form-group">
                  <label>End Date</label>
                    <div class="input-group date" id="reservationdatetime1" data-target-input="nearest">
                        <input asp-for = "End_Date" type="text" class="form-control datetimepicker-input" data-target="#reservationdatetime1"/>
                        <div class="input-group-append" data-target="#reservationdatetime1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>

              <div class="form-group">
                <label for="inputName">Give A point</label>
                <input asp-for="Point" type="number" id="inputName" class="form-control" placeholder="choose number between 1 - 1000">
              </div>

              <div class="form-group">
                <label>Add Files Here</label>
                <input type="file" name="subtaskfiles"  multiple required>
              </div>

            
          <div class="form-group">
        <div class="col-12">
          <a href="# class="btn btn-secondary">Cancel</a>
          <input type="submit" value="Create new Project" class="btn btn-success float-right">
        </div>
      </div>

            </div>

           
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      

      </div>
      
       </form>
</section>

Views/SubTask/Detail.cshtml
@using ProjectManagementApp.Models
@model SubTaskDetail
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Sub-Task Detail Info</h1>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">Sub-Task Detail</h3>
    </div>
    <div class="card-body">
        <div class="row">
        <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
            <div class="row">
            <div class="col-12 col-sm-5">
                <div class="info-box bg-light">
                <div class="info-box-content">
                    <span class="info-box-text text-center text-muted">Start Date</span>
                    <span class="info-box-number text-center text-muted mb-0">@Model.SubTask.Start_Date</span>
                </div>
                </div>
            </div>
            <div class="col-12 col-sm-5">
                <div class="info-box bg-light">
                <div class="info-box-content">
                    <span class="info-box-text text-center text-muted">End Date</span>
                    <span class="info-box-number text-center text-muted mb-0">@Model.SubTask.End_Date</span>
                </div>
                </div>
            </div>
            <div class="col-12 col-sm-2">
                <div class="info-box bg-light">
                <div class="info-box-content">
                    <span class="info-box-text text-center text-muted">Estimated project duration</span>
                    <span class="info-box-number text-center text-muted mb-0">20</span>
                </div>
                </div>
            </div>
            </div>
            
            <div class="row">
            <div class="col-12">
                <h4>@Model.SubTask.Description</h4>
                <p></p>
                <p class="text-muted">Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terr.</p>
            </div>
            </div>
        </div>
        <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
            <h5 class="mt-5 text-muted">SubTask 
                files</h5>
             <ul class="list-unstyled">
                @foreach(var tf in Model.SubTaskFiles){
                  
                  <li>
                    @if(tf.ContentType.StartsWith("image/")){
                         <i class="fas fa-file-image" style="color:blue;"></i>
                         <a href="@Url.Action("GetSubTaskFile", "SubTask", new { id = tf.Id })">
                            Download @tf.FileName
                        </a>
                    }
                    else if(tf.ContentType == "application/pdf"){
                      <i class="fas fa-file-pdf" style="color:red;"></i>
                      <a href="@Url.Action("GetSubTaskFile", "SubTask", new { id = tf.Id })">
                            Download @tf.FileName
                        </a>
                    }
                    else if(tf.ContentType == "application/msword"){
                      <i class="fas fa-file-word"></i>
                      <a href="@Url.Action("GetSubTaskFile", "SubTask", new { id = tf.Id })">
                            Download @tf.FileName
                        </a>
                    }
                    else{
                      <i class="fas fa-file" style="color:gray;"></i>
                      <a href="@Url.Action("GetSubTaskFile", "SubTask", new { id = tf.Id })">
                            Download @tf.FileName
                        </a>
                    }
                 
                  </li>
                }
              </ul>
        <a asp-controller = "Task" asp-action = "TaskDetail" asp-route-Id = "@Model.SubTask.TaskId" class="badge badge-danger">Back</a>
        @if(Model.SubTask.Status != "Completed"){
        <a asp-controller = "SubTask" asp-action = "StatusUpdate" asp-route-Id = "@Model.SubTask.Id" class="badge badge-success">Complete</a>
            }
        </div>
        </div>
    </div>
    <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>